name: Deploy Nginx with Ansible

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH directory
        run: mkdir -p .ssh

      - name: Set up SSH private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > .ssh/azure_macbookpro.pem
          chmod 600 .ssh/azure_macbookpro.pem

      - name: Create known_hosts file
        run: |
          # Add each host to known_hosts
          ssh-keyscan -H 20.160.156.107 >> .ssh/known_hosts
          ssh-keyscan -H 20.160.156.142 >> .ssh/known_hosts
          ssh-keyscan -H 20.160.156.98 >> .ssh/known_hosts
          ssh-keyscan -H 20.160.156.133 >> .ssh/known_hosts
          ssh-keyscan -H 20.160.156.127 >> .ssh/known_hosts
          chmod 600 .ssh/known_hosts

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory install_nginx.yml
